import { MoonIcon, SunIcon } from "@radix-ui/react-icons"
import {
    Mail, 
    Monitor, 
    X, 
    Menu, 
    Clipboard, 
    ClipboardCheck, 
    CloudDownload, 
    Send,
    HardHat,
    RotateCcw,
    Bell,
    ChevronLeft,
    ChevronRight,
    Phone,
    MapPin,
    ArrowUpRight,
    CircleCheck,
    CircleX
} from 'lucide-react';

export const Icons = {
    close: X,
    burgerMenu: Menu,
    sun: SunIcon,
    moon: MoonIcon,
    monitor: Monitor,
    mail: Mail,
    send: Send,
    clipboard: Clipboard,
    clipboardCheck: ClipboardCheck,
    download: CloudDownload,
    construction:HardHat,
    reload:RotateCcw,
    bell: Bell,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    phone: Phone,
    location: MapPin,
    externLink: ArrowUpRight,
    circleCheck: CircleCheck,
    circleX: CircleX,
}